// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.core.irrigacion.domain.ubicacion;

import com.core.irrigacion.domain.ubicacion.Provincia;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Provincia_Roo_Configurable {
    
    declare @type: Provincia: @Configurable;
    
}
