// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.core.irrigacion.domain;

import com.core.irrigacion.domain.Estado;

privileged aspect Estado_Roo_JavaBean {
    
    public String Estado.getEstado() {
        return this.estado;
    }
    
    public void Estado.setEstado(String estado) {
        this.estado = estado;
    }
    
}
