// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.core.irrigacion.domain;

import com.core.irrigacion.domain.Inspeccion;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Inspeccion_Roo_Configurable {
    
    declare @type: Inspeccion: @Configurable;
    
}
