// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.core.irrigacion.domain;

import com.core.irrigacion.domain.Inspector;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Inspector_Roo_Configurable {
    
    declare @type: Inspector: @Configurable;
    
}
