// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.core.irrigacion.domain;

import com.core.irrigacion.domain.TipoCausa;

privileged aspect TipoCausa_Roo_JavaBean {
    
    public String TipoCausa.getTipoCausa() {
        return this.tipoCausa;
    }
    
    public void TipoCausa.setTipoCausa(String tipoCausa) {
        this.tipoCausa = tipoCausa;
    }
    
}
